# Generated by Django 3.0.2 on 2020-02-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('essay', models.CharField(max_length=1000)),
            ],
        ),
    ]
